src/app/urls.py
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView, TokenVerifyView

from django.contrib import admin
from django.urls import path, include

API_VERSION = 'api/v1'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('social.urls')),

    path(f'{API_VERSION}/token/', TokenObtainPairView.as_view(), name='token_obtain_pair'),
    path(f'{API_VERSION}/token/refresh/', TokenRefreshView.as_view(), name='token_refresh'),
    path(f'{API_VERSION}/token/verify/', TokenVerifyView.as_view(), name='token_verify'),
    path(f'{API_VERSION}/social/', include('social.api.urls'))
]

src/social/api/urls.py
from django.urls import path

from . import views

app_name = 'api'

urlpatterns = [
    path('likes/analitics', views.analitics, name='analitics'),
    path('user/stat', views.user_stat, name='user_stat'),
    path('posts/create', views.create_post, name='create_post'),
    path('user/login_view', views.login_view, name='login'),
]

src/social/urls.py
from django.urls import path

from . import views

app_name = 'social'

urlpatterns = [
    path('', views.index, name='index'),
    # Accounts views
    path('login', views.login_view, name='login'),
    path('logout', views.logout_view, name='logout'),
    path('register', views.register_view, name='register'),

    # Posts views
    path('posts/create', views.create_post, name='create'),
    path('posts/<int:id>', views.toggle_like_model, name='toggle_like'),
]

src/social/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.


class User(AbstractUser):
    last_request = models.DateTimeField(null=True, blank=True)

    def serialize(self):
        return {
            'email': self.email,
            'last_login': self.last_login,
            'last_request': self.last_request
        }


class Post(models.Model):
    header = models.CharField(max_length=512)
    text = models.TextField(max_length=1000)
    creation_date = models.DateTimeField(auto_now_add=True)
    edit_date = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(to=User, on_delete=models.CASCADE, related_name="author")
    likes = models.ManyToManyField(to=User, related_name="likes")

    @property
    def likes_count(self):
        # count = len(self.likes.all())
        count = self.like_set.all().count()
        return count


class Like(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    like_date = models.DateTimeField(auto_now_add=True)

    def serialize(self):
        return {
            'id': self.id,
            'post': self.post.header,
            'like_date': self.like_date.strftime("%b %-d %Y, %-I:%M %p")
        }

src/social/forms.py
from django.forms import ModelForm

from .models import Post


class PostCreateForm(ModelForm):
    class Meta:
        model = Post
        fields = [
            'header',
            'text',
        ]

src/social/api/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response

from django.http import JsonResponse
from django.contrib.auth import authenticate, login

from social.models import Like, Post, User


@api_view(['GET'])
def analitics(request):
    response = {}
    date_from = request.GET['date_from']
    date_to = request.GET['date_to']
    likes_list = Like.objects.filter(like_date__range=[date_from, date_to])
    for i, like in enumerate(likes_list):
        response[i] = like.serialize()
    response['total'] = likes_list.count()
    return Response(response)


@api_view(['GET'])
def user_stat(request):
    response = {}
    users = User.objects.all()
    for i, user in enumerate(users):
        response[i] = user.serialize()
    return Response(response)


@api_view(['POST'])
def create_post(request):
    header = request.POST['header']
    text = request.POST['text']
    author = request.user
    Post.objects.create(
        header=header,
        text=text,
        author=author,
    )
    return JsonResponse({'message': f'Post {header} created sucessfully'})


@api_view(['POST'])
def login_view(request):
    email = request.POST["email"]
    password = request.POST["password"]
    user = authenticate(request, username=email, password=password)
    login(request, user)
    return JsonResponse({'message': f'Logged it as {email}'})

src/social/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib.auth import authenticate, login, logout
from django.db import IntegrityError
from django.urls import reverse
from social.forms import PostCreateForm
from django.contrib.auth.decorators import login_required

from social.models import Like, User, Post


# Create your views here.
def index(request):
    return render(request, 'social/index.html', {
        'posts': Post.objects.all(),
    })


def login_view(request):
    if request.method == "POST":
        email = request.POST["email"]
        password = request.POST["password"]
        user = authenticate(request, username=email, password=password)

        if user is not None:
            login(request, user)
            return HttpResponseRedirect(reverse('social:index'))
        else:
            return render(request, "social/login.html", {
                "message": "Invalid email and/or password."
            })
    else:
        return render(request, 'social/login.html')


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))


def register_view(request):
    if request.method == "POST":
        email = request.POST['email']
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password != confirm_password:
            return render(request, '')

        try:
            user = User.objects.create_user(email, email, password)
            user.save()
        except IntegrityError as e:
            print(e)
            return render(request, "social/register.html", {
                "message": "Email address already taken."
            })
        login(request, user)
        return HttpResponseRedirect(reverse("social:index"))
    else:
        return render(request, "social/register.html")


def create_post(request):
    if request.method == 'POST':
        form = PostCreateForm(request.POST)
        if form.is_valid():
            form = form.save(commit=False)
            form.author = request.user
            form.save()
            return render(request, "social/index.html", {
                "message": "Post created and published."
            })
        else:
            return render(request, 'social/create.html', {
                'form': form
            })
    else:
        form = PostCreateForm()
        return render(request, 'social/create.html', {
                'form': form
            })


def toggle_like(request, id):
    post = Post.objects.get(id=id)
    user = request.user
    if user in post.likes.all():
        post.likes.remove(user)
    else:
        post.likes.add(user)
    return HttpResponseRedirect(reverse("social:index"))


@login_required(login_url='/social/login/')
def toggle_like_model(request, id):
    post = Post.objects.get(id=id)
    user = request.user
    like, created = Like.objects.get_or_create(
        user=user,
        post=post,
    )
    if created:
        return HttpResponseRedirect(reverse("social:index"))
    else:
        like.delete()
        return HttpResponseRedirect(reverse("social:index"))

src/social/templates/social/create.html
{% extends 'social/layout.html' %}

{% block body %}
<form method="POST">
    {% csrf_token %}

    {{ form.as_p }}
    
    <input class="btn btn-light" type="submit" value="Create">
</form>
{% endblock %}

src/social/templates/social/index.html
{% extends 'social/layout.html' %}

{% block title %}Index{% endblock %}
{% block body %}
    <a href="{% url 'social:create' %}">Create post</a>
    {% for post in posts %}
    <div style="padding-top: 30px;">
        <h2>{{post.header}}</h2>
        <p>{{ post.text }}</p>
        <p><a href="{% url 'social:like_unlike' post.id %}">Like</a> {{ post.likes_count }}</p>
        <p>Posted by: {{ post.author.username }} at {{ post.creation_date.date }}</p>
    </div>
    {% endfor %}

{% endblock %}

src/social/templates/social/layout.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Mail{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        {% block script %}
        {% endblock %}
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
            <a class="navbar-brand" href="#">Navbar</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNavDropdown">
              <ul class="navbar-nav">
                <li class="nav-item active">
                  <a class="nav-link" href="{% url 'social:index' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'social:logout' %}">Log out</a>
                </li>
                <li class="nav-item">
                    Logged in as: {{ user.email }}
                </li>
                {% else %}
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'social:login' %}">Log in</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'social:register' %}">Register</a>
                </li>
                {% endif %}
                </ul>
            </div>
          </nav>
        <div>{% if message %}{{ message }}{% endif %}</div>
        <div class="container">
            {% block body %}
            {% endblock %}
        </div>
    </body>
</html>

src/social/templates/social/login.html
{% extends 'social/layout.html' %}

{% block title %}Log in{% endblock %}

{% block body %}
    <form action="{% url 'social:login' %}" method="POST">
        {% csrf_token %}
        <div class="form-group">
            <input autofocus class="form-control" type="email" name="email" placeholder="Email">
        </div>
        <div class="form-group">
            <input class="form-control" type="password" name="password" placeholder="Password">
        </div>
        <input class="btn btn-primary" type="submit" value="Login">
    </form>
    Don't have an account? <a href="{% url 'social:register' %}">Register here.</a>

{% endblock %}

src/social/templates/social/register.html
{% extends 'social/layout.html' %}

{% block body %}
<form action="{% url 'social:register' %}" method="post">
    {% csrf_token %}
    <div class="form-group">
        <input class="form-control" type="email" name="email" placeholder="Email Address">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="password" placeholder="Password">
    </div>
    <div class="form-group">
        <input class="form-control" type="password" name="confirm_password" placeholder="Confirm Password">
    </div>
    <input class="btn btn-primary" type="submit" value="Register">
</form>

Already have an account? <a href="{% url 'social:login' %}">Log In here.</a>
{% endblock %}